force-app/main/default/objects/MaskSObject__c/MaskSObject__c.object-meta.xml
<CustomObject>
    <description>Contains information about the sobject to mask</description>
    <label>Mask SObject</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObject__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API Name of the SObject to mask</description>
    <label>API Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MaskSObject__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Indicates the order of execution of this object</description>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MaskSObject__c/fields/WhereClause__c.field-meta.xml
<CustomField>
    <fullName>WhereClause__c</fullName>
    <description>Restrict the SObject query by adding a WHERE clause</description>
    <label>Where Clause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/MaskSObjectField__c.object-meta.xml
<CustomObject>
    <description>Records which fields to mask and how to mask it</description>
    <label>Mask SObject Field</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObjectField__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Indicate the action to perform on this field to mask data</description>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Erase</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Obfuscate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API of the field to mask</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/fields/MaskSObject__c.field-meta.xml
<CustomField>
    <fullName>MaskSObject__c</fullName>
    <description>Link of the SObject&apos;s field</description>
    <label>Mask SObject</label>
    <referenceTo>MaskSObject__c</referenceTo>
    <relationshipLabel>Mask SObject Fields</relationshipLabel>
    <relationshipName>MaskSObjectFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MaskSObjectBatchTest.cls
@isTest
private class MaskSObjectBatchTest {

	private static String NAME = 'Test Mask Data';
	private static String PHONE = '0606060606';
	private static String LASTNAME = 'Doe';
	private static String ASSISTANTNAME = 'Jane DOE';
	private static String EMAIL = 'jdoe@masksobject.com';

	@TestSetup
	static void makeData(){
		List<MaskSObject__c> sobjMask = new List<MaskSObject__c>{
			new MaskSObject__c(Sequence__c = 1, APIName__c = 'Account'),
			new MaskSObject__c(Sequence__c = 2, APIName__c = 'Contact', WhereClause__c = 'AssistantName != null')
		};
		insert sobjMask;

		List<MaskSObjectField__c> fieldMask = new List<MaskSObjectField__c>{
			new MaskSObjectField__c(MaskSObject__c = sobjMask.get(0).Id, APIName__c = 'Name', Action__c = MaskSObjectConstants.ACTION_OBFUSCATE),
			new MaskSObjectField__c(MaskSObject__c = sobjMask.get(0).Id, APIName__c = 'Phone', Action__c = MaskSObjectConstants.ACTION_ERASE),
			new MaskSObjectField__c(MaskSObject__c = sobjMask.get(1).Id, APIName__c = 'LastName', Action__c = MaskSObjectConstants.ACTION_OBFUSCATE),
			new MaskSObjectField__c(MaskSObject__c = sobjMask.get(1).Id, APIName__c = 'AssistantName', Action__c = MaskSObjectConstants.ACTION_ERASE),
			new MaskSObjectField__c(MaskSObject__c = sobjMask.get(1).Id, APIName__c = 'Email', Action__c = MaskSObjectConstants.ACTION_OBFUSCATE)
		};
		insert fieldMask;

		insert new Account(Name = NAME, Phone = PHONE);
		insert new Contact(FirstName = 'John', LastName = LASTNAME, AssistantName = ASSISTANTNAME, Email = EMAIL);
	}

	@isTest
	static void maskSobjectTest(){

		Test.startTest();
		Database.executeBatch(new MaskSObjectBatch());
		Test.stopTest();

		Account acc = [SELECT Id, Name, Phone FROM Account LIMIT 1];
		System.assertNotEquals(NAME, acc.Name, 'The account name should be masked');
		System.assertNotEquals(PHONE, acc.Phone, 'The account phone should be masked');

		Contact cont = [SELECT Id, LastName, AssistantName, Email FROM Contact LIMIT 1];
		System.assertNotEquals(LASTNAME, cont.LastName, 'The contact lastname should be masked');
		System.assertNotEquals(ASSISTANTNAME, cont.AssistantName, 'The contact AssistantName should be masked');
		System.assertNotEquals(EMAIL, cont.Email, 'The contact Email should be masked');
	}
}