force-app/main/default/objects/MaskSObject__c/MaskSObject__c.object-meta.xml
<CustomObject>
    <description>Contains information about the sobject to mask</description>
    <label>Mask SObject</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObject__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API Name of the SObject to mask</description>
    <label>API Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MaskSObject__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Scope size</description>
    <inlineHelpText>The optimal scope size is a factor of 2000, for example, 100, 200, 400 and so on.</inlineHelpText>
    <label>Batch size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/MaskSObject__c/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Indicates the order of execution of this object</description>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/MaskSObject__c/fields/WhereClause__c.field-meta.xml
<CustomField>
    <fullName>WhereClause__c</fullName>
    <description>Restrict the SObject query by adding a WHERE clause</description>
    <label>Where Clause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/MaskSObjectField__c.object-meta.xml
<CustomObject>
    <description>Records which fields to mask and how to mask it</description>
    <label>Mask SObject Field</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObjectField__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Indicate the action to perform on this field to mask data</description>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Erase</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Obfuscate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/fields/APIName__c.field-meta.xml
<CustomField>
    <fullName>APIName__c</fullName>
    <description>API of the field to mask</description>
    <externalId>true</externalId>
    <label>API Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/fields/MaskSObject__c.field-meta.xml
<CustomField>
    <fullName>MaskSObject__c</fullName>
    <description>Link of the SObject&apos;s field</description>
    <label>Mask SObject</label>
    <referenceTo>MaskSObject__c</referenceTo>
    <relationshipLabel>Mask SObject Fields</relationshipLabel>
    <relationshipName>MaskSObjectFields</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/MaskSObjectUtils.cls
public with sharing class MaskSObjectUtils {

	/**
	 * @description  Returns the list of MaskSObject__c after the sequence parameter
	 * @param sequence
	 * @return  `List<MaskSObject__c>`
	 */
	public static List<MaskSObject__c> getMaskSObjectList(Integer sequence){
		return [SELECT APIName__c, Sequence__c, WhereClause__c, BatchSize__c
			,(SELECT APIName__c, Action__c FROM MaskSObjectFields__r) FROM MaskSObject__c
			WHERE Sequence__c >:sequence ORDER BY Sequence__c];
	}

	/**
	 * @description Returns a random string based on the length char number
	 * @param len
	 * @return  `String`
	 */
	private static String getRandomString(Integer len){
		Blob blobKey = Crypto.generateAesKey(128);
		String key = EncodingUtil.base64encode(blobKey);
		return key.substring(0, len > key.length() ? key.length() : len);
	}

	/**
	 * @description Returns a the val input obfuscated (some char replaced by 'x' and numbers by 0)
	 * @param val
	 * @return  `String`
	 */
	private static String obfuscate(String val){
		Set<String> chars = new Set<String> {'a', 'e', 'i', 'o', '1', '2', '5', '6'};
		for(String chr : chars){
			val = val.toLowerCase().replaceAll(chr, chr.isNumeric() ? '0' : 'x');
		}
		return val;
	}

	public static void maskField(Map<String, Schema.DisplayType> fieldType, MaskSObjectField__c field, SObject sobj){
		String val = (String)sobj.get(field.APIName__c);
		if(val != null){
			String retVal;

			if(MaskSObjectConstants.ACTION_ERASE.equals(field.Action__c)){
				retVal = null;
			} else {
				String prefix = '';
				String suffix = '';

				switch on fieldType.get(field.APIName__c) {
					when EMAIL{
						//keep the email suffix to create a valid email address
						suffix = '@' + val.substringAfter('@');
						val = val.substringBefore('@');
					}
					when PHONE{
						//keep the prefix to prevent VR errors
						Integer phonePrefixIndex = 2;
						prefix = val.left(phonePrefixIndex);
						val = val.substringAfter(prefix);
					}
				}

				if(MaskSObjectConstants.ACTION_RANDOMIZE.equals(field.Action__c)){
					val = getRandomString(val.length());
				} else if(MaskSObjectConstants.ACTION_OBFUSCATE.equals(field.Action__c)){
					val = obfuscate(val);
				}
				retVal = prefix + val + suffix;
			}
			sobj.put(field.APIName__c, retVal);
		}
	}
}