force-app/main/default/objects/MaskSObject__c/MaskSObject__c.object-meta.xml
<CustomObject>
    <description>Contains information about the sobject to mask</description>
    <label>Mask SObject</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObject__c/fields/BatchSize__c.field-meta.xml
<CustomField>
    <fullName>BatchSize__c</fullName>
    <description>Scope size</description>
    <inlineHelpText>The optimal scope size is a factor of 2000, for example, 100, 200, 400 and so on.</inlineHelpText>
    <label>Batch size</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MaskSObjectSandboxPostCopy.cls
global with sharing class MaskSObjectSandboxPostCopy implements SandboxPostCopy {

	global void runApexClass(SandboxContext context) {
		List<MaskSObject__c> settings = MaskSObjectUtils.getMaskSObjectList(0);
		if(!settings.isEmpty()){
			Integer batchSize = settings.get(0).BatchSize__c != null ? settings.get(0).BatchSize__c : 200;
			Database.executeBatch(new MaskSObjectBatch(), batchSize);
		}
	}
}