force-app/main/default/objects/MaskSObjectField__c/MaskSObjectField__c.object-meta.xml
<CustomObject>
    <description>Records which fields to mask and how to mask it</description>
    <label>Mask SObject Field</label>
    <nameField>
        <label>Mask SObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mask SObject Fields</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/MaskSObjectField__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>Indicate the action to perform on this field to mask data</description>
    <label>Action</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Erase</fullName>
            </value>
            <value>
                <fullName>Replace</fullName>
            </value>
            <value>
                <fullName>Obfuscate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/MaskSObjectField__c/fields/ActionType__c.field-meta.xml
<CustomField>
    <fullName>ActionType__c</fullName>
    <description>Indicates the type of action configured</description>
    <label>Action Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Action__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardcoded</fullName>
            </value>
            <value>
                <fullName>Dictionary.firstname</fullName>
                <label>Dictionary Firstname</label>
            </value>
            <value>
                <fullName>Dictionary.fullname</fullName>
                <label>Dictionary Fullname</label>
            </value>
            <value>
                <fullName>Dictionary.lastname</fullName>
                <label>Dictionary Lastname</label>
            </value>
            <value>
                <fullName>Regex</fullName>
                <isActive>false</isActive>
                <label>Regex</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/MaskSObjectConstants.cls
public with sharing class MaskSObjectConstants {

	/**
	 * MaskSObjectField__c
	 */

	//Action__c
	public static final String ACTION_ERASE = 'Erase';
	public static final String ACTION_REPLACE = 'Replace';
	public static final String ACTION_OBFUSCATE = 'Obfuscate';
	public static final String ACTION_RANDOMIZE = 'Randomize';
	public static final String ACTION_LUHN = 'Random Luhn number';

	//ActionType__c
	public static final String ACTION_TYPE_HARDCODED = 'Hardcoded';
	public static final String ACTION_TYPE_DICT = 'Dictionary';
	public static final String ACTION_TYPE_DICT_FIRST = ACTION_TYPE_DICT + '.firstname';
	public static final String ACTION_TYPE_DICT_LAST = ACTION_TYPE_DICT + '.lastname';
	public static final String ACTION_TYPE_DICT_FULL = ACTION_TYPE_DICT + '.fullname';
	public static final String ACTION_TYPE_DICT_EMAIL = ACTION_TYPE_DICT + '.email';
	public static final String ACTION_TYPE_DICT_COMPANY = ACTION_TYPE_DICT + '.company';
	public static final String ACTION_TYPE_DICT_STREET = ACTION_TYPE_DICT + '.street';
}